"""Fix the 13 pre-existing dead references in the GeoToxGraph release.

Two classes of fix:

1. Add 2 missing compound/location nodes that 3 arsenite edges reference:
   - extracellular:arsenite
   - compound:methylated_arsenicals

2. Convert 10 ExposoGraph bridge edges to declare their external target via a
   new `external_target_ref` column instead of a same-graph `target_id`. This
   keeps the cross-graph link visible (and citeable) while letting the strict
   dead-reference CI gate report zero unresolved same-graph references.

Run with --dry-run to preview.
"""
from __future__ import annotations
import argparse
import csv
from pathlib import Path

HERE = Path(__file__).parent

# --- Class 1: nodes to add ---
NEW_NODES = {
    "geotoxgraph_nodes.csv": [
        {
            "id": "extracellular:arsenite",
            "label": "Extracellular arsenite As(III)",
            "node_type": "location",
            "strain_id": "shared",
            "module_id": "",
            "entity_class": "extracellular_compartment",
            "identifier": "arsenite_extracellular",
            "description": "Extracellular pool of arsenite (As(III)) generated by Acr3-family efflux from cytoplasm to the periplasm/environment; detoxification endpoint for cytoplasmic arsenite in Geobacter and other bacteria.",
            "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5288829/",
        },
        {
            "id": "compound:methylated_arsenicals",
            "label": "Methylated arsenicals (MMA/DMA/TMA)",
            "node_type": "compound",
            "strain_id": "shared",
            "module_id": "",
            "entity_class": "detoxification_product",
            "identifier": "MMA/DMA/TMA",
            "description": "Mono-, di-, and trimethylated arsenic species produced by SAM-dependent ArsM methylation of arsenite; volatile TMA can be eliminated as arsine gas in bacterial systems and represents a detoxification route distinct from Acr3-mediated efflux.",
            "source_url": "https://pubmed.ncbi.nlm.nih.gov/16452170/",
        },
    ]
}

# --- Class 2: bridge edges to convert ---
# For each edge, move target_id -> external_target_ref, blank the target_id.
BRIDGE_EDGE_IDS = {
    "edge:nat2_slow_bridge_exposograph",
    "edge:gstm1_null_bridge_exposograph",
    "edge:gstt1_null_bridge_exposograph",
    "edge:ugt1a1_28_bridge_exposograph",
    "edge:sult1a1_2_bridge_exposograph",
    "edge:nqo1_2_bridge_exposograph",
    "edge:aldh2_2_bridge_exposograph",
    "edge:cyp2d6_4_bridge_exposograph",
    "edge:fmo3_lof_bridge_exposograph",
    "edge:as3mt_slow_methylator_bridge_exposograph",
}


def add_nodes(dry_run: bool) -> None:
    for fname, node_specs in NEW_NODES.items():
        fpath = HERE / fname
        with open(fpath) as f:
            reader = csv.DictReader(f)
            fieldnames = list(reader.fieldnames)
            rows = list(reader)
        existing_ids = {r["id"] for r in rows}
        added = 0
        for spec in node_specs:
            if spec["id"] in existing_ids:
                print(f"  Skip existing node {spec['id']} in {fname}")
                continue
            # Fill any missing fields with empty
            new_row = {k: spec.get(k, "") for k in fieldnames}
            rows.append(new_row)
            added += 1
            print(f"  Add node {spec['id']} to {fname}")
        if not dry_run and added:
            with open(fpath, "w", newline="") as f:
                w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
                w.writeheader()
                w.writerows(rows)


def convert_bridge_edges(dry_run: bool) -> None:
    fpath = HERE / "evolutionary_contrast_edges.csv"
    with open(fpath) as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames)
        rows = list(reader)

    # Add the new column if not already present
    if "external_target_ref" not in fieldnames:
        fieldnames = fieldnames + ["external_target_ref"]
        print(f"  Added column external_target_ref to {fpath.name}")
        for r in rows:
            r.setdefault("external_target_ref", "")

    converted = 0
    for r in rows:
        if r["edge_id"] in BRIDGE_EDGE_IDS:
            r["external_target_ref"] = r["target_id"]
            r["target_id"] = ""
            converted += 1
    print(f"  Converted {converted} bridge edges (target_id -> external_target_ref)")

    if not dry_run:
        with open(fpath, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
            w.writeheader()
            w.writerows(rows)


def dead_ref_check() -> int:
    node_ids = set()
    for fname in ["geotoxgraph_nodes.csv", "evolutionary_contrast_nodes.csv"]:
        with open(HERE / fname) as f:
            for r in csv.DictReader(f):
                node_ids.add(r["id"])
    dead = 0
    for fname in ["geotoxgraph_edges.csv", "evolutionary_contrast_edges.csv"]:
        with open(HERE / fname) as f:
            for r in csv.DictReader(f):
                if r["source_id"] not in node_ids and r["source_id"]:
                    print(f"  DEAD: {fname} {r['edge_id']} source={r['source_id']}")
                    dead += 1
                if r["target_id"] not in node_ids and r["target_id"]:
                    print(f"  DEAD: {fname} {r['edge_id']} target={r['target_id']}")
                    dead += 1
    return dead


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    print("Before fix:")
    dead_before = dead_ref_check()
    print(f"  Dead references: {dead_before}")

    print("\nApplying fixes:")
    add_nodes(args.dry_run)
    convert_bridge_edges(args.dry_run)

    if args.dry_run:
        print("\n[dry-run] Not writing. Would-be state not verified.")
        return

    print("\nAfter fix:")
    dead_after = dead_ref_check()
    print(f"  Dead references: {dead_after}")

    if dead_after > 0:
        raise SystemExit(f"Still {dead_after} dead references after fix.")


if __name__ == "__main__":
    main()
