"""Regenerate confidence_score and overclaim_flags in evolutionary_contrast_edges.csv
using build_confidence_and_summary.py's canonical rubric.

After the v6 audit revision, the paper's central methodological claim is that
every score in the release can be regenerated by rerunning the script. This
script does exactly that and writes the results back so the claim holds.

Run this after any change to the confidence-relevant fields (evidence_tier,
evidence_type, notes, source_url, predicate, target_id, module_id) or to the
scoring code.
"""
import csv
from pathlib import Path

HERE = Path(__file__).parent

# Import the canonical rubric
import sys
sys.path.insert(0, str(HERE))
from build_confidence_and_summary import confidence_and_flags


def main():
    fpath = HERE / "evolutionary_contrast_edges.csv"
    with open(fpath, newline="") as f:
        reader = csv.DictReader(f)
        fieldnames = list(reader.fieldnames)
        rows = list(reader)

    n_score_changes = 0
    n_flag_changes = 0
    n_score_penalized = 0
    n_score_boosted = 0

    for r in rows:
        new_score, new_flags = confidence_and_flags(r)
        if r.get("confidence_score") != new_score:
            try:
                old = float(r["confidence_score"])
                new = float(new_score)
                if new < old:
                    n_score_penalized += 1
                else:
                    n_score_boosted += 1
            except (ValueError, KeyError):
                pass
            r["confidence_score"] = new_score
            n_score_changes += 1
        if r.get("overclaim_flags") != new_flags:
            r["overclaim_flags"] = new_flags
            n_flag_changes += 1

    with open(fpath, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
        w.writeheader()
        w.writerows(rows)

    print(f"Regenerated confidence columns on {len(rows)} contrast edges:")
    print(f"  confidence_score changes: {n_score_changes}")
    print(f"    (penalized: {n_score_penalized}, boosted: {n_score_boosted})")
    print(f"  overclaim_flags changes: {n_flag_changes}")

    # Quick equality test: rerun and confirm no more changes
    with open(fpath, newline="") as f:
        rows2 = list(csv.DictReader(f))
    diffs = 0
    for r in rows2:
        new_score, new_flags = confidence_and_flags(r)
        if r["confidence_score"] != new_score or r["overclaim_flags"] != new_flags:
            diffs += 1
    print(f"\nSecond-pass equality test: {diffs} residual differences")
    if diffs != 0:
        raise SystemExit(f"Rubric is not idempotent: {diffs} rows differ after one pass.")


if __name__ == "__main__":
    main()
